language: android
android:
    components:
        - build-tools-22.1.2
        - android-21
        - extra-google-google_play_services
        - addon-google_apis-google-21
        - sys-img-armeabi-v7a-android-21
        - sys-img-x86-android-21
before_script:
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
