language: android
android:
    components:
        - build-tools-19.1.0
        - android-19
        - android-22
        - extra-google-google_play_services
        - addon-google_apis-google-19
        - sys-img-x86-android-19
